### ISSUE TITLE
오픈소스 고유 툴바(파일 생성, 삭제, 이름 변경) 버그 및 카피 미구현

### ISSUE THREAD

**Issue by keylime7** [bagzaru/simple_git_gui#21]
오픈소스에 기본적으로 있던 new, delete, rename, copy에 문제가 있습니다.

new: 생성할때마다 오류 메시지 뜨는데, 새로고침하면 생성 되어 있음
delete, rename: 오픈 소스 때부터, git gui 개발 중반까지만해도 오류 메시지만 뜨고 적용은 됐는데, 지금은 아예 적용 안됨
copy: 원래부터 버튼이랑 함수만 있고 연동이 안되어 있었음(함수가 제대로 작동하는지 미확인)

copy는 시간상 걍 날려야할거 같은데
나머지는 버그 찾거나, 아니면 optional이니 그냥 포기하거나 해야할 듯 합니다.

만약 시간 있으면 수정 부탁, 저도 시간 있으면 할게요

**Comment by bagzaru** [comment]
Copy는 Directory카피까지 구현하기에는 시간이 모자랍니다. 우선 Copy, Rename 기능을 제한두었습니다.
