### ISSUE TITLE
JGitManagerImprv 함수 리스트

### ISSUE THREAD

**Issue by min-jp** [bagzaru/simple_git_gui#26]
### 함수 리스트
기본적으로 모든 함수는 예외처리가 되어있음. 예외가 던져지면 오류창 띄워주세요.
파라미터 중 File nowDir은 현재의 디렉토리를 파일 형태로 넘겨주면 됩니다.

`void gitClone(File fileToClone, String cloneURL)`
클론

`void setIdToken(String ID, String accessToken)`
id와 토큰 세팅

`String getID()`
id 리턴

`String getAccessToken()`
AccessToken 리턴

`void gitCreateBranch(File nowDir, String branchName)`
브랜치 생성

`void gitDeleteBranch(File nowDir, String branchName)`
브랜치 삭제

`void gitRenameBranch(File nowDir, String oldName, String newName)`
브랜치 rename

`void gitMerge(File nowDir, String sourceBranch)`
현재 branch에서 source branch를 merge

`void gitCheckout(File nowDir, String branchName)`
브랜치 체크아웃

`String gitCurrentBranch(File nowDir)`
현재 디렉토리에 체크아웃되어있는 브랜치 이름 리턴

`CommitInfo gitCommitInfo(RevCommit nowCommit)`
현재 커밋을 넘겨주면 그에 대한 정보를 리턴
CommitInfo는 새로 정의한 클래스
CommitInfo안에 get함수들을 통해 정보를 받아올 수 있음
```
String getCheckSum()
String getCommitTime()
String getCommitMessage()
String getAuthorName()
String getAuthorEMail()
```

`Set<File> gitChangedFileList(File nowDir, RevCommit nowCommit)`
특정 commit에서 변경된 파일 리스트를 가져옴

`String gitDiff(File nowDir, RevCommit nowCommit, File changedFile)`
특정 커밋의 특정 파일의 변경사항을 문자열로 반환
nowCommit은 현재 커밋
changedFile은 변경사항을 알고 싶은 파일 객체

`Set<String> gitBranchList (File nowDir)`
전체 branch 리스트

**Comment by psae0714** [comment]
좋아요!

**Comment by min-jp** [comment]
사용완료
