### ISSUE TITLE
BranchPanel 크기 조절

### ISSUE THREAD

**Issue by bagzaru** [bagzaru/simple_git_gui#35]
현재 브랜치 패널의 내부 크기 조정이 필요

**Comment by bagzaru** [comment]
이승재(keylime7)가 진행중

**Comment by keylime7** [comment]
BranchPanel 크기 조절 완료 (FilePanel에서 설정된 크기를 디폴트로 기반)

FilePanel 메뉴 쪽 사이즈가 체계화 되지 않게 설정되어 있으나
문제는 없기에 그 부분은 수정 x
